#!/usr/bin/env python3
"""Generate embedded content modules for the Vercel build.

Two TS modules are produced so the app never reads files at runtime
(Vercel lambdas only see traced imports, not the whole repo tree):

- src/lib/agent/h3-content.ts  — the MiniMax H3 prompt-writing skill docs
- src/lib/kernels.ts           — the 4 Kaggle worker/studio notebooks
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # repo root


def ts_export(name: str, raw: str) -> str:
    # JSON-encode the whole payload: safe inside single quotes, handles
    # backticks/${} that would otherwise break template literals.
    return f"export const {name} = {json.dumps(raw)};\n"


h3_dir = os.path.join(ROOT, "src", "lib", "agent", "h3")
skill = open(os.path.join(h3_dir, "h3-skill.md"), encoding="utf-8").read()
base = open(os.path.join(h3_dir, "h3-base-en.txt"), encoding="utf-8").read()

with open(os.path.join(ROOT, "src", "lib", "agent", "h3-content.ts"), "w", encoding="utf-8") as f:
    f.write("// AUTO-GENERATED by scripts/embed_content.py — do not edit by hand.\n")
    f.write("// Source: src/lib/agent/h3/* (MiniMax H3 prompt-writing skill)\n")
    f.write(ts_export("H3_SKILL_MD", skill))
    f.write(ts_export("H3_BASE_EN", base))
print("h3-content.ts written")

kernel_dir = os.path.join(ROOT, "kernels")
os.makedirs(kernel_dir, exist_ok=True)
# notebooks come from the proven sandbox pipeline
SRC_KERNELS = "/home/z/my-project/studio-data/kernel-src"
names = [
    "rmc_studio_real.ipynb",
    "rmc_studio_test.ipynb",
    "rmc_studio_worker_real.ipynb",
    "rmc_studio_worker_test.ipynb",
]
with open(os.path.join(ROOT, "src", "lib", "kernels.ts"), "w", encoding="utf-8") as f:
    f.write("// AUTO-GENERATED by scripts/embed_content.py — do not edit by hand.\n")
    f.write("// Kaggle notebook sources pushed verbatim via the REST API.\n")
    for n in names:
        raw = open(os.path.join(SRC_KERNELS, n), encoding="utf-8").read()
        var = n.replace(".ipynb", "").upper()
        f.write(ts_export(f"KERNEL_{var}", raw))
        # also keep a copy of the notebook in the repo for reference
        with open(os.path.join(kernel_dir, n), "w", encoding="utf-8") as kf:
            kf.write(raw)
print("kernels.ts written + notebooks copied to kernels/")
